### ISSUE TITLE
MultiSafepay\ConnectCore\Service\OrderService::canChangePaymentMethod() must be of the type string, null given

### ISSUE THREAD

**Issue by Asitis** [MultiSafepay/magento2#14]
I'm not sure if this is new since the latest .1 update, but I'm noticing these errors in our logs. Does this have to do with the public  transaction validation perhaps?

We're running Magento 2.4.1, and 2.8.1 of your core MSP module.

```[2021-05-27 07:18:15] main.CRITICAL: TypeError: Argument 2 passed to MultiSafepay\ConnectCore\Service\OrderService::canChangePaymentMethod() must be of the type string, null given, called in /opt/magento/public_html/vendor/multisafepay/magento2-core/Service/OrderService.php on line 237 and defined in /opt/magento/public_html/vendor/multisafepay/magento2-core/Service/OrderService.php:304
Stack trace:
#0 /opt/magento/public_html/vendor/multisafepay/magento2-core/Service/OrderService.php(237): MultiSafepay\ConnectCore\Service\OrderService->canChangePaymentMethod()
#1 /opt/magento/public_html/vendor/multisafepay/magento2-frontend/Controller/Connect/Notification.php(92): MultiSafepay\ConnectCore\Service\OrderService->processOrderTransaction()
#2 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(58): MultiSafepay\ConnectFrontend\Controller\Connect\Notification->execute()
#3 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(138): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->___callParent()
#4 /opt/magento/public_html/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->Magento\Framework\Interception\{closure}()
#5 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute()
#6 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(153): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->Magento\Framework\Interception\{closure}()
#7 /opt/magento/public_html/generated/code/MultiSafepay/ConnectFrontend/Controller/Connect/Notification/Interceptor.php(23): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->___callPlugins()
#8 /opt/magento/public_html/vendor/magento/framework/App/Action/Action.php(111): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->execute()
#9 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#10 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(138): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->___callParent()
#11 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(153): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->Magento\Framework\Interception\{closure}()
#12 /opt/magento/public_html/generated/code/MultiSafepay/ConnectFrontend/Controller/Connect/Notification/Interceptor.php(32): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->___callPlugins()
#13 /opt/magento/public_html/vendor/magento/framework/App/FrontController.php(186): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->dispatch()
#14 /opt/magento/public_html/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest()
#15 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#16 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#17 /opt/magento/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#18 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#19 /opt/magento/public_html/vendor/mirasvit/module-cache-warmer/src/CacheWarmer/Plugin/Debug/OnHitPlugin.php(140): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#20 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\CacheWarmer\Plugin\Debug\OnHitPlugin->aroundAroundDispatch()
#21 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}()
#22 /opt/magento/public_html/generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php(23): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins()
#23 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch()
#24 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#25 /opt/magento/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#26 /opt/magento/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#27 /opt/magento/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#28 /opt/magento/public_html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
#29 /opt/magento/public_html/pub/index.php(40): Magento\Framework\App\Bootstrap->run()
#30 {main} [] []
[2021-05-27 07:18:16] main.CRITICAL: TypeError: Argument 2 passed to MultiSafepay\ConnectCore\Service\OrderService::canChangePaymentMethod() must be of the type string, null given, called in /opt/magento/public_html/vendor/multisafepay/magento2-core/Service/OrderService.php on line 237 and defined in /opt/magento/public_html/vendor/multisafepay/magento2-core/Service/OrderService.php:304
Stack trace:
#0 /opt/magento/public_html/vendor/multisafepay/magento2-core/Service/OrderService.php(237): MultiSafepay\ConnectCore\Service\OrderService->canChangePaymentMethod()
#1 /opt/magento/public_html/vendor/multisafepay/magento2-frontend/Controller/Connect/Notification.php(92): MultiSafepay\ConnectCore\Service\OrderService->processOrderTransaction()
#2 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(58): MultiSafepay\ConnectFrontend\Controller\Connect\Notification->execute()
#3 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(138): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->___callParent()
#4 /opt/magento/public_html/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->Magento\Framework\Interception\{closure}()
#5 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute()
#6 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(153): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->Magento\Framework\Interception\{closure}()
#7 /opt/magento/public_html/generated/code/MultiSafepay/ConnectFrontend/Controller/Connect/Notification/Interceptor.php(23): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->___callPlugins()
#8 /opt/magento/public_html/vendor/magento/framework/App/Action/Action.php(111): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->execute()
#9 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#10 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(138): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->___callParent()
#11 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(153): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->Magento\Framework\Interception\{closure}()
#12 /opt/magento/public_html/generated/code/MultiSafepay/ConnectFrontend/Controller/Connect/Notification/Interceptor.php(32): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->___callPlugins()
#13 /opt/magento/public_html/vendor/magento/framework/App/FrontController.php(186): MultiSafepay\ConnectFrontend\Controller\Connect\Notification\Interceptor->dispatch()
#14 /opt/magento/public_html/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest()
#15 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#16 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#17 /opt/magento/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#18 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#19 /opt/magento/public_html/vendor/mirasvit/module-cache-warmer/src/CacheWarmer/Plugin/Debug/OnHitPlugin.php(140): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#20 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\CacheWarmer\Plugin\Debug\OnHitPlugin->aroundAroundDispatch()
#21 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}()
#22 /opt/magento/public_html/generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php(23): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins()
#23 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch()
#24 /opt/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#25 /opt/magento/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#26 /opt/magento/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#27 /opt/magento/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#28 /opt/magento/public_html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
#29 /opt/magento/public_html/pub/index.php(40): Magento\Framework\App\Bootstrap->run()
#30 {main} [] []
```

**Comment by vinodsowdagar** [comment]
Hi @Asitis ,

Thank you for the report.

We were aware of this issue happening with the 'MultiSafepay' payment method. Can you confirm that you are using this payment method in your environment as well? If so, we have created a fix for this internally that will be added to the next release.

Looking forward to your reply.

**Comment by Asitis** [comment]
Hi Vinod,

We're seeing this error on multiple shops, but none of them use the 'MultiSafePay' payment method; it's disabled everywhere. For instance, shops in France and UK where 99% of the payments happen via VISA/Mastercard, and in the Netherlands where it's mostly iDeal.

**Comment by vinodsowdagar** [comment]
Hi @Asitis ,

We have fixed this issue and it will be added to the next release this week.
As soon as this is done, we will give you an update.

**Comment by vinodsowdagar** [comment]
Hi @Asitis ,

We have released a new version of our extension, which should fix this issue:
https://github.com/MultiSafepay/magento2/releases/tag/2.9.0

Please reopen the issue or create a new one if you are still finding problems.
